Continue instead of crashing when objects are missing
This can happen with submodules.

Closes #3

Before:

```
Error: Failed to collect commits from repository

Caused by:
    0: Object find error: An object with id fdb30228b1dc649ab1c2086d146ef9dd0ab584e6 could not be found
    1: An object with id fdb30228b1dc649ab1c2086d146ef9dd0ab584e6 could not be found
```

After:

```
⠋ Collecting commits...                                                                                   Warning: Object find error: An object with id fdb30228b1dc649ab1c2086d146ef9dd0ab584e6 could not be found
⠦ Collecting commits...                                                                                   Warning: Object find error: An object with id fc412cbdf765175ea9f3380db6b9e1b1603a68a7 could not be found
⠤ Collecting commits...                                                                                   Warning: Object find error: An object with id b699a7e01c253ffb7818b02d62bce24190ec1019 could not be found
⠁ Collecting commits...                                                                                   Warning: Object find error: An object with id b699a7e01c253ffb7818b02d62bce24190ec1019 could not be found
  Commits collected
```

Not the prettiest, but better than a crash!